"""
HTML report generator — produces a self-contained single-file backtest summary.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from engine.backtest import BacktestResult


def generate_html_report(
    result: BacktestResult,
    bah: pd.Series,
    ticker: str,
    strategy: str,
    start_date: str,
    end_date: str,
    benchmark_metrics: dict | None = None,
) -> str:
    """
    Generate a self-contained HTML string with embedded Plotly charts.
    The output opens in any browser without network access.
    """
    m = result.metrics

    # ---- Equity + Drawdown subplots ----
    fig = make_subplots(
        rows=2, cols=1, shared_xaxes=True, row_heights=[0.7, 0.3],
        vertical_spacing=0.05,
    )
    fig.add_trace(go.Scatter(x=result.equity.index, y=result.equity,
                             name="Strategy", line=dict(color="#2ecc71", width=2)), row=1, col=1)
    fig.add_trace(go.Scatter(x=bah.index, y=bah,
                             name="Buy & Hold", line=dict(color="#95a5a6", dash="dash")), row=1, col=1)
    fig.add_trace(go.Scatter(x=result.drawdown.index, y=result.drawdown * 100,
                             fill="tozeroy", name="Drawdown %",
                             line=dict(color="#e74c3c"),
                             fillcolor="rgba(231,76,60,0.25)"), row=2, col=1)
    fig.update_layout(title=f"{ticker} — {strategy}", height=520, template="plotly_dark")
    fig.update_yaxes(title_text="Portfolio ($)", row=1)
    fig.update_yaxes(title_text="Drawdown (%)", row=2)
    chart_html = fig.to_html(include_plotlyjs="cdn", full_html=False)

    # ---- KPI table ----
    kpis = [
        ("CAGR", f"{m.get('cagr', 0)*100:.1f}%"),
        ("Sharpe", f"{m.get('sharpe', 0):.2f}"),
        ("Sortino", f"{m.get('sortino', 0):.2f}"),
        ("Max Drawdown", f"{m.get('max_drawdown', 0)*100:.1f}%"),
        ("Win Rate", f"{m.get('win_rate', 0)*100:.1f}%"),
        ("Profit Factor", f"{m.get('profit_factor', 0):.2f}"),
        ("# Trades", str(m.get("n_trades", 0))),
        ("Total Return", f"{m.get('total_return', 0)*100:.1f}%"),
    ]
    kpi_rows = "\n".join(
        f"<tr><td>{k}</td><td><strong>{v}</strong></td></tr>" for k, v in kpis
    )

    bm_section = ""
    if benchmark_metrics and "error" not in benchmark_metrics:
        bm_rows = "\n".join(
            f"<tr><td>{k.replace('_', ' ').title()}</td><td><strong>{v}</strong></td></tr>"
            for k, v in benchmark_metrics.items()
        )
        bm_section = f"""
        <h2>Benchmark Metrics vs SPY</h2>
        <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:340px">
        {bm_rows}
        </table>
        """

    # ---- Trade log table ----
    if not result.trades.empty:
        trade_table = result.trades.to_html(index=False, classes="trade-table", border=0)
    else:
        trade_table = "<p><em>No completed trades.</em></p>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Backtest Report — {ticker} / {strategy}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #0e1117; color: #fafafa; padding: 20px; }}
  h1 {{ color: #2ecc71; }}
  h2 {{ color: #95a5a6; border-bottom: 1px solid #333; padding-bottom: 4px; }}
  table {{ border-collapse: collapse; margin-bottom: 24px; }}
  td, th {{ padding: 6px 14px; border: 1px solid #333; }}
  th {{ background: #1a1a2e; }}
  .trade-table th {{ background: #1a1a2e; font-size: 12px; }}
  .trade-table td {{ font-size: 12px; }}
  .meta {{ color: #aaa; font-size: 14px; margin-bottom: 20px; }}
</style>
</head>
<body>
<h1>Backtest Report</h1>
<p class="meta">
  <strong>Ticker:</strong> {ticker} &nbsp;|&nbsp;
  <strong>Strategy:</strong> {strategy} &nbsp;|&nbsp;
  <strong>Period:</strong> {start_date} to {end_date}
</p>

<h2>Performance Metrics</h2>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:340px">
{kpi_rows}
</table>

{bm_section}

<h2>Equity Curve & Drawdown</h2>
{chart_html}

<h2>Trade Log</h2>
{trade_table}

<hr style="border-color:#333;margin-top:32px">
<p style="color:#555;font-size:12px">
  Generated by Quant Trading App · For research and educational purposes only.
  Backtested results do not guarantee future performance.
</p>
</body>
</html>
"""
    return html
